name: Web
on: workflow_dispatch
jobs:
  HTML5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 8.0.2
          haxelib install openfl 9.1.0
          haxelib --never install flixel 5.3.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.5.0 --quiet
          haxelib install flixel-addons 3.1.1 --quiet
          haxelib install tjson --quiet
          haxelib install hxCodec 2.6.1 --quiet
          haxelib git luajit https://github.com/nebulazorua/linc_luajit --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib list


      - name: Compile
        run: haxelib run lime build html5 -final

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: export/release/html5/bin
          if-no-files-found: error
